{"title":"cv2:ImportError: libGL.so.1","date":"2020-12-22T04:46:53.000Z","date_formatted":{"ll":"Dec 22, 2020","L":"12/22/2020","MM-DD":"12-22"},"link":"2020/12/22/cv2ImportError libGL.so.1","comments":true,"tags":["Python"],"updated":"2020-12-22T04:46:53.000Z","content":"<p>import cv2</p>\n<p>ImportError: libGL.so.1: cannot open shared object file: No such file or directory</p>\n<figure class=\"highlight bash\"><table><tr><td class=\"gutter\"><pre><span class=\"line\">1</span><br><span class=\"line\">2</span><br></pre></td><td class=\"code\"><pre><span class=\"line\">sudo apt update</span><br><span class=\"line\">sudo apt install libgl1-mesa-glx</span><br></pre></td></tr></table></figure>\n","prev":{"title":"Image similarity","link":"2020/12/27/Image similarity"},"next":{"title":"python play list(2nd)","link":"2020/12/07/python play list(2nd)"},"plink":"http://thswind.github.io/2020/12/22/cv2ImportError libGL.so.1/","reading_time":"27 words in 1 min"}